### ISSUE TITLE
Make crash in this case:

### ISSUE THREAD

**Issue by Karaulov** [TsudaKageyu/minhook#54] opened 2017-09-25 13:41 UTC
Any ways to fix it ?

After hook:
![udzokly 1](https://user-images.githubusercontent.com/6445336/30811151-0a2ec1b0-a210-11e7-8008-219c114995b4.png)

Function prototype and pseudocode:
![mo4rgke 1](https://user-images.githubusercontent.com/6445336/30811171-1c1e70e6-a210-11e7-960b-06f48d374cff.png)

Original asm:
![k3dbmjl 1](https://user-images.githubusercontent.com/6445336/30811287-5f9bc170-a210-11e7-8c3b-262676cd0b3b.png)

**Comment by Karaulov** [comment] 2017-09-25 13:46
Minhook still does not support this?

**Comment by RaMMicHaeL** [comment] 2017-09-26 09:19
That's a duplicate of:
https://github.com/TsudaKageyu/minhook/issues/44

**Closed** 2017-09-26 10:52 UTC
